# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b7c92f3423459610ab3819fed6f4bfd323f00b161fb9a6571376a374b92b3a2407168752651e542ea39d30ba57d938f11d9f0b50a292c3896301e8d997bad3

test:
  secret_key_base: 75308ccf5cfc50d7d226d62ee29518e62e942d1021bf21fa3c2552a7aa82f2400b286d231c6fba40459d46ec58df3e4ab752a631aa23da931c4b17db2e3ee65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
